name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  macos:
    runs-on: macos-latest

    strategy:
      matrix:
        xcode:
          - "11.7" # Swift 5.2
          - "12" # Swift 5.3

    name: "macOS (Xcode ${{ matrix.xcode }})"

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Test
        run: swift test
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

  linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        swift: ["5.3", "5.2"]

    name: "Linux (Swift ${{ matrix.swift }})"

    container:
      image: swift:${{ matrix.swift }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Test
        run: swift test --enable-test-discovery
